version: "3"
services:
  app:
    build:
      context: .
      target: runtime
      args:
        RAILS_ENV: ${RAILS_ENV:-development}
    depends_on:
      - vite
    environment:
      VITE_RUBY_HOST: vite
      RAILS_LOG_TO_STDOUT: yes
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - /app/node_modules
      - /app/public/docs

  vite:
    build:
      context: .
      target: runtime
      args:
        RAILS_ENV: ${RAILS_ENV:-development}
    entrypoint: bin/vite dev
    environment:
      DEBUG: "*vite*"
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
    ports:
      - "3036:3036"
    volumes:
      - .:/app
      - /app/node_modules

  muffet:
    depends_on:
      - app
    build:
      context: .
      target: muffet
    entrypoint:
      - /work/muffet.rb
    working_dir: /work
    volumes:
      - .buildkite/steps:/work
    environment:
      BUILDKITE: ${BUILDKITE:-false}

  deploy-preview:
    build:
      context: .
      target: deploy-preview
      args:
        RAILS_ENV: ${RAILS_ENV:-development}
    volumes:
      - ".:/app"
      - /app/node_modules
      - /app/public/docs
