#docs-private-to-public-sync
notify:
  - slack: "$SLACK_CHANNEL"
    if: build.state != "passed"

steps:
  - label: Sync to public mirror
    branches: main
    commands: |
      echo "+++ :git: Syncing to public mirror"

      git push "https://dummy-user:$${GH_TOKEN}@github.com/buildkite/docs.git" ${BUILDKITE_COMMIT}:main
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-docs-private
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
      - aws-ssm#v1.0.0:
          parameters:
            GH_TOKEN: /pipelines/buildkite/docs-private/gh-token
