env:
  BUILDKIT_PROGRESS: plain

steps:
  - label: "Prepare preview"
    command: bin/prepare-preview
    key: prepare-preview
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-docs-private
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
      - aws-ssm#v1.0.0:
          parameters:
            GH_TOKEN: /pipelines/buildkite/docs-private/gh-token
            BUILDKITE_ANALYTICS_TOKEN: /pipelines/buildkite/docs-private/buildkite-analytics-token
            NETLIFY_AUTH_TOKEN: /pipelines/buildkite/docs-private/netlify-auth-token
            NETLIFY_SITE_ID: /pipelines/buildkite/docs-private/netlify-site-id

  - label: "Deploy preview"
    command: bin/deploy-preview
    depends_on: prepare-preview
    env:
      RAILS_ENV: "production"
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-docs-private
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
      - aws-ssm#v1.0.0:
          parameters:
            GH_TOKEN: /pipelines/buildkite/docs-private/gh-token
            BUILDKITE_ANALYTICS_TOKEN: /pipelines/buildkite/docs-private/buildkite-analytics-token
            NETLIFY_AUTH_TOKEN: /pipelines/buildkite/docs-private/netlify-auth-token
            NETLIFY_SITE_ID: /pipelines/buildkite/docs-private/netlify-site-id
      - docker-compose#v3.9.0:
          run: deploy-preview
          dependencies: false
          mount-buildkite-agent: true
          env:
            - GH_REPO
            - GH_TOKEN
            - NETLIFY_AUTH_TOKEN
            - NETLIFY_SITE_ID
            - NETLIFY_SALT
            - BUILDKITE_BRANCH
