env:
  BUILDKIT_PROGRESS: plain

steps:
  - label: ":spider: muffet"
    # We need to wait until rails has started before running muffet as otherwise it will error out
    # and the test will appear to have failed without having run. The time to wait is hard to
    # predict, and furthermore, some paths take longer to be be ready than others. The path in this
    # loop was chosen after some non-systematic observations. So it does not guarantee that the
    # server will be ready. But it seems to work well in practice.
    command: >-
      while ! wget --spider -Sq http://app:3000/docs/agent/v3/hooks;
        do echo 💎🛤️🦥 Rails is still starting;
        sleep 0.5;
      done &&
      echo 💎🛤️🚆 Rails has started running &&
      /muffet http://app:3000/docs \
        --include="/docs/" \
        --exclude="https://github.com/buildkite/docs/" \
        --exclude="buildkite.com/docs" \
        --max-connections=10 \
        --buffer-size=8192 \
        --color=always
    env:
      RAILS_ENV: production
    agents:
      queue: hosted
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-docs
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
      - ecr#v2.9.0:
          login: true
          account-ids: public.ecr.aws
      - docker-compose#v3.9.0:
          run: muffet
          shell: false
          upload-container-logs: always
          env:
            - RAILS_ENV

  - label: ":graphql: Check generated code is up to date"
    command: bundle exec rake graphql:generate
    agents:
      queue: hosted
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-docs
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
      - ecr#v2.9.0:
          login: true
          account-ids: public.ecr.aws
      - docker-compose#v3.9.0:
          run: app
          dependencies: false
      - .buildkite/plugins/check-for-changes:
          fail_message: "Generated code is out of date. Run `bundle exec rake graphql:generate` and commit the changes."

  - group: "Lint all the things"
    key: linting
    steps:
      - label: ":prettier: Lint assets"
        commands:
          - yarn
          - npm run prettier-check
        agents:
          queue: hosted
        plugins:
          - aws-assume-role-with-web-identity#v1.4.0:
              role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-docs
              session-tags:
                - organization_slug
                - organization_id
                - pipeline_slug
          - ecr#v2.9.0:
              login: true
              account-ids: public.ecr.aws
          - docker#v3.7.0:
              image: "public.ecr.aws/docker/library/node:lts-alpine3.16"

      - label: ":lint-roller: Linting text and markdown"
        agents:
          queue: hosted
        plugins:
          - docker-compose#v3.9.0:
              run: vale
              config: ./vale/docker-compose.yml

      - label: ":lint-roller: Linting for insensitive words"
        command: npm run lint -y
        agents:
          queue: hosted
        plugins:
          - aws-assume-role-with-web-identity#v1.4.0:
              role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-docs
              session-tags:
                - organization_slug
                - organization_id
                - pipeline_slug
          - ecr#v2.9.0:
              login: true
              account-ids: public.ecr.aws
          # Using the plain Node image, instead of the custom doc Dockerfile
          # version, is way faster because we don't have to wait for Ruby gems to
          # install.
          - docker#v3.7.0:
              image: "public.ecr.aws/docker/library/node:lts-alpine3.16"

      - label: "Validate YAML"
        command:
          - npm run -y validate-agent-attributes-yaml
          - npm run -y validate-environment-variables-yaml
        agents:
          queue: hosted
        plugins:
          - aws-assume-role-with-web-identity#v1.4.0:
              role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-docs
              session-tags:
                - organization_slug
                - organization_id
                - pipeline_slug
          - ecr#v2.9.0:
              login: true
              account-ids: public.ecr.aws
          - docker#v3.7.0:
              image: "public.ecr.aws/docker/library/node:lts-alpine3.16"

      - label: ":lint-roller: :markdown: Linting the Markdown"
        command: npm run -y mdlint
        agents:
          queue: hosted
        plugins:
          - aws-assume-role-with-web-identity#v1.4.0:
              role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-docs
              session-tags:
                - organization_slug
                - organization_id
                - pipeline_slug
          - ecr#v2.9.0:
              login: true
              account-ids: public.ecr.aws
          - docker#v3.7.0:
              image: "public.ecr.aws/docker/library/node:lts-alpine3.16"

      - label: ":snake: Linting markdown files for snake case"
        command: npx -y @ls-lint/ls-lint@2.1.0
        agents:
          queue: hosted
        plugins:
          - aws-assume-role-with-web-identity#v1.4.0:
              role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-docs
              session-tags:
                - organization_slug
                - organization_id
                - pipeline_slug
          - ecr#v2.9.0:
              login: true
              account-ids: public.ecr.aws
          - docker#v3.7.0:
              image: "public.ecr.aws/docker/library/node:lts-alpine3.16"

  - label: ":rspec: RSpec"
    depends_on: linting
    command: bundle exec rspec
    artifact_paths: "log/rspec-*.xml"
    key: "rspec"
    env:
      RAILS_ENV: test
    agents:
      queue: hosted
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-docs
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
      - ecr#v2.9.0:
          login: true
          account-ids: public.ecr.aws
      - docker-compose#v3.9.0:
          run: app
          dependencies: false
          env:
            - BUILDKITE_ANALYTICS_TOKEN
            - BUILDKITE_BRANCH
            - BUILDKITE_BUILD_ID
            - BUILDKITE_BUILD_NUMBER
            - BUILDKITE_BUILD_URL
            - BUILDKITE_COMMIT
            - BUILDKITE_JOB_ID
            - BUILDKITE_MESSAGE
            - CI
            - RAILS_ENV

  - label: ":docker: Build image"
    depends_on: "linting"
    key: "assets"
    env:
      RAILS_ENV: production
    agents:
      queue: hosted
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-docs
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
      - ecr#v2.9.0:
          login: true
          account-ids: public.ecr.aws
      - docker-compose#v3.9.0:
          build: app

  - label: ":junit: Test Summary"
    depends_on: "rspec"
    allow_dependency_failure: true
    agents:
      queue: hosted
    plugins:
      - bugcrowd/test-summary#v1.11.0:
          inputs:
            - label: ":rspec: RSpec"
              artifact_path: "log/rspec*"
              type: junit
          formatter:
            type: details
          context: test-summary
