link_checking_exemptions:
  - name: ignore-all-errors
    description: |
      Ignore all errors.
      All failures are ignored for these prefixes.
    status_pattern: ".*"
    url_patterns:
      - https://github.com/buildkite/docs/
      - https://buildkite.com/my-organization/
      - https://github.com/my-org/
      - https://claude.ai/download

  - name: login-required
    description: |
      Ignore HTTP 403 Forbidden.
      URLs matching these regular expressions are known not to work unless you are logged in.
    status_pattern: "403"
    url_patterns:
      - https://buildkite.com/organizations/
      - https://buildkite.com/user/
      - https://buildkite.com/(~|%7E)/
      - https://portal.azure.com/

  - name: accept-anti-scraping-measures
    description: Muffet resembles a scraper to some sites
    status_pattern: "(400|403)"
    url_patterns:
      - https://www.npmjs.com/
      - https://linux.die.net/man/
      - https://www.seek.com.au/
      - https://www.cvedetails.com/
      - https://github.com/marketplace
      - https://codepen.io/
      - https://www.java.com
      - https://jsonschemalint.com/


  - name: ignore-api-401-unauthorized
    description: Ignore HTTP 401 Unauthorized on Buildkite API
    status_pattern: "401"
    url_patterns:
      - https://api.buildkite.com/

  - name: accept-429-too-many-requests
    description: Ignore rate limiting.
    status_pattern: "429"
    url_patterns:
      # Everything
      - ".*"

  - name: fragments-handled-by-js-not-html
    description: Sites that interpret URL fragments using JS, rather than standard browser behavior
    status_pattern: "id #.* not found"
    url_patterns:
      - https://github.com/
      - https://cd.apps.argoproj.io/swagger-ui
      - https://docs.cursor.com/

  - name: surprising-fragment-failures
    description: Surprisingly, these links fail because of missing anchors, not authentication.
    status_pattern: "id #.* not found"
    url_patterns:
      - https://console.cloud.google.com/compute/instancesAdd
      - https://console.aws.amazon.com/cloudformation/home
      - https://console.aws.amazon.com/ec2/v2/home

  - name: ignore-sample-dot-svg
    description: We don't expect /sample.svg to work on the test server that Muffet uses.
    status_pattern: "404"
    url_patterns:
      - "http://app:3000/sample.svg\\?"

  - name: not-actually-links
    description: Muffet can be a bit greedy sometimes, and pick up URLs that are not actually links, but (for example) part of code samples.
    status_pattern: ".*"
    url_patterns:
      - https://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
